### PR TITLE
PR REQUEST FOR Backend Server Set Up #7

### PR DESCRIPTION
**Pull request by rishyym0927**
Hello @monarxxjain  , This is the PR request for issue ->Backend Server Set Up #7

**Pull Request Description:**

This pull request addresses the need to create two servers within the backend folder: one using Node.js (`server1.js`) and the other using Express.js (`server2.js`). Each server is configured to listen on ports 5000 and 5001, respectively. Additionally, an environment file (`env.js`) is implemented for managing variables like port numbers and other potential future additions.

1. Set up a simple Node.js server to listen on port 5000.
2. Configure an Express server to listen on port 5001.
3. Implement an environment file for managing variables such as port numbers and potential future additions.

In the README.md file, a section is added with an appropriate heading to address the following questions:

- Is it advisable to have multiple servers in the backend of a project? Why or why not?
- Does the decision to use multiple servers depend on the project requirements?
- If yes, what factors should influence the decision to use multiple servers, and what actions should be taken accordingly?

This pull request enhances the project's organization and lays the groundwork for future scalability and configuration management.

### CODE REVIEW

**Comment by monarxxjain** [comment]
Great start @rishyym0927,
But to ensure proper handling of environment variables, please name the file as `.env` not _env.js_, and configure a script such as **npm start** or **npm run dev** to run `server2.js` inside the Backend folder.

**Comment by rishyym0927** [comment]
hello @monarxxjain  sir, 
I have made some new commits
I have changed my server1 and server2 js files , removed my env.js and converted it into .env file. Also I have initiales a script for server2.js. Also I have installed a dependency of dotenv to configure the.env files

**Comment by monarxxjain** [comment]
Thanks for your contribution to the project! 
I've noticed a couple of things that need addressing before we merge this Pull Request.

**Missing .env File and Unignored /Backend/node_modules:**
It seems like the _.env_ file hasn't been added to the repository, and the `/Backend/node_modules` directory is not ignored in the _.gitignore_ file. It's crucial to include the _.env_ file for environment configurations, and the node_modules directory should definitely be ignored to prevent unnecessary bloat in the repository. Let's make sure to add the .env file and update the .gitignore accordingly.

**ExpressJS Dependency in server2.js:**
I've observed that server2.js is attempting to run without ExpressJS, but there's no express dependency listed in the package.json file within the Backend directory. Since server2.js relies on ExpressJS functionality, we need to ensure that the appropriate dependency is included in the package.json file. Let's add ExpressJS as a dependency.

Please address these issues, and once done, feel free to ping me for another review. Keep up the good work!

**Comment by monarxxjain** [comment]
In instances where a maintainer requests changes, please refrain from creating a new pull request. Instead, commit the changes to the existing branch and continue on the same pull request. Kindly adhere to this practice for your future contributions.
Anyways I will see your new PR now.

**Pull request closed without merging**
