### PR TITLE
Added custom 404 not found page. Fixes : #4

### PR DESCRIPTION
**Pull request by MrImmortal09**
Hello @monarxxjain , This is the recreated PR for the issue Create Custom 404 Page https://github.com/iiitl/Wollete/issues/4 and these are the following chnages I have made in PR.

Changes Made
Designed and created a custom 404 page that seamlessly integrates with the website's theme and design elements.
Modified the routing system to ensure that the custom 404 page is displayed when users navigate to non-existent routes.
Added clear indication on the custom 404 page to inform users that the requested page could not be found.

As per the conversation I have reopened the PR

Screenshot from 2024-03-15 04-46-17

@monarxxjain please review

### CODE REVIEW

**Comment by monarxxjain** [comment]
Great start @MrImmortal09,
It would be better if we remove the footer and make this page Non-scrollable, also you can add a button that will redirect to homepage.
Once done these we can merge you PR

**Comment by MrImmortal09** [comment]
Ok @monarxxjain I have got it and I will be back soon with the fixes

**Comment by MrImmortal09** [comment]
I have added a new component ImagewithButton and used it in the 404 not found page, This will enhance the look as well as serve as a button to Home page.

Screenshot from 2024-03-15 17-47-11

**Comment by MrImmortal09** [comment]
@monarxxjain , Please review this PR

**Comment by monarxxjain** [comment]
@MrImmortal09  Yea now it looks good, but still there are some BUGs in reponsiveness of this page.
Between 786px to 1280px screen appears to be blank. Seems a minor fix to me. Do that and we will be good to go.

**Comment by MrImmortal09** [comment]
@monarxxjain I didn't get it, Can you please describe the bug in brief (or else in a short video or anotation on a image).

**Comment by monarxxjain** [comment]
Here is glimpse of the BUG I am talking about:-
https://github.com/iiitl/Wollete/assets/128830789/de88ceae-ecf6-44b4-8464-785d62feb694

**Comment by MrImmortal09** [comment]
@monarxxjain I don't know why but it looks good on my side. Please check the attached video. 
[Screencast from 2024-03-17 15-36-29.webm](https://github.com/iiitl/Wollete/assets/48794764/c9a7a2a3-874a-4638-901d-04f240499bad)

**Pull request closed without merging**
